### PR TITLE
Clarify homogeneous ensembles comments

### LINKED ISSUE #945: Make docs regarding Random Forest and Ensebles more clear
From https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/:
"[Homogeneous Ensembles](https://alan-turing-institute.github.io/MLJ.jl/dev/homogeneous_ensembles/#Homogeneous-Ensembles) - for blending the predictions of multiple supervised models all of the same type, but which receive different views of the training data to reduce overall variance. The technique is known as observation [bagging](https://en.wikipedia.org/wiki/Bootstrap_aggregating). **Bagging decision trees, like a DecisionTreeClassifier, gives what is known as a random forest, although MLJ also provides several canned random forest models.**"

The quote suggests (to me at least) that an Ensemble of trees is equivalent to a random forest. However, from https://en.wikipedia.org/wiki/Random_forest#:~:text=Random%20forests%20or%20random%20decision,class%20selected%20by%20most%20trees.:
"An extension of the algorithm was developed by [Leo Breiman](https://en.wikipedia.org/wiki/Leo_Breiman)[[9]](https://en.wikipedia.org/wiki/Random_forest#cite_note-breiman2001-9) and [Adele Cutler](https://en.wikipedia.org/wiki/Adele_Cutler),[[10]](https://en.wikipedia.org/wiki/Random_forest#cite_note-rpackage-10) who registered[[11]](https://en.wikipedia.org/wiki/Random_forest#cite_note-11) "Random Forests" as a [trademark](https://en.wikipedia.org/wiki/Trademark) in 2006 (as of 2019, owned by [Minitab, Inc.](https://en.wikipedia.org/wiki/Minitab)).[[12]](https://en.wikipedia.org/wiki/Random_forest#cite_note-12) The extension combines Breiman's "[bagging](https://en.wikipedia.org/wiki/Bootstrap_aggregating)" idea and random selection of features, introduced first by Ho[[1]](https://en.wikipedia.org/wiki/Random_forest#cite_note-ho1995-1) and later independently by Amit and [Geman](https://en.wikipedia.org/wiki/Donald_Geman)[[13]](https://en.wikipedia.org/wiki/Random_forest#cite_note-amitgeman1997-13) in order to construct a collection of decision trees with controlled variance."

Of particular interest is "and random selection of features", which is not an option for Ensembles as far as I can tell. This difference between a random forest and ensemble of trees should be made more clear in the docs, or potentially the option to only classify by a random subset of features should be added to ensembles.

### PR DESCRIPTION
**Pull request by ablaom**
To close #945

### CODE REVIEW

**Comment by ablaom** [comment]
@KronosTheLate

**Comment by KronosTheLate** [comment]
I am completely happy with the content of the suggestion. It does however feel too verbose to me, so I suggest a rewrite from
"
variance. The technique implemented here is known as observation [bagging](https://en.wikipedia.org/wiki/Bootstrap_aggregating). (In the special case of decision trees, further randomness is normally
introduced by subsampling *features* when training each node ([Ho (1995)](https://web.archive.org/web/20160417030218/http://ect.bell-labs.com/who/tkh/publications/papers/odt.pdf), [Brieman and 
 utler (2001)](https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm)).  In `DecisionTreeClassifier` from  DecisionTree.jl, for example, you can control feature subsampling with the `n_subfeatures` hyper-parameter. See the [Random 
 Forest Wikipedia page](https://en.wikipedia.org/wiki/Random_forest) for details on this combination. Run models("RandomForest")` to see canned random forest implementations provided by MLJ.)"

to 
"variance. The technique implemented here is known as observation [bagging](https://en.wikipedia.org/wiki/Bootstrap_aggregating). For example,  a heterogeneous ensemble of Decision Trees essentially produces a Random Forest, without the feature subsampling found in some versions of random Forest. (You can run `models("RandomForest")` to see canned random forest implementations provided by MLJ that provide feature subsampling.)"

**Comment by ablaom** [comment]
@KronosTheLate I've moved out that detail to the dedicated "Homgeneous Ensembles" section, which now also points to examples from Data Science Tutorials of using `EnsembleModel` to construct what I'm now sure is a bona fide random forest.

**Comment by KronosTheLate** [comment]
"An bagged ensemble of such trees is known as a [Random
Forest](https://en.wikipedia.org/wiki/Random_forest)."

Should be "A bagged ensemble", right?

**Comment by KronosTheLate** [comment]
As a general note, would it be desirable to enable automated spell-checking for documentations?
It would be caught automatically:
image

**Comment by ablaom** [comment]
@KronosTheLate Thanks for the correction. Fixed on dev.

> As a general note, would it be desirable to enable automated spell-checking for documentations?
It would be caught automatically:

How do you set this up?

**Comment by KronosTheLate** [comment]
No idea, but it has got to be doable. E.g. grammarly checks writing in the browser, so it would be possible to check everything by editing via the web interface. But a more elegant solution that I cant think of was what I was hoping for.

**Pull request merged**
