### PR TITLE
CI: fix the YAML syntax for the docs job, and thus properly surface any docbuild failures

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes the "silent" part of #1045 

Obviously doesn't actually fix the underlying doc failure.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ablaom This is now ready for review.

**Comment by ablaom** [comment]
@OkonSamuel Can you please review this and follow up? I think we need a PR to master to test the current fail is detected.

**Comment by DilumAluthge** [comment]
I can push a commit to this branch to demonstrate that it detects the failure.

**Comment by DilumAluthge** [comment]
@ablaom As you can see on the test commit https://github.com/alan-turing-institute/MLJ.jl/pull/1046/commits/d66d8291acd213adfd39530adebfeb121144352b, we correctly detect the docs failure.

**Comment by ablaom** [comment]
Thanks @DilumAluthge . I'm convinced. If you could kindly restore to previous state we can merge.

**Comment by OkonSamuel** [comment]
@DilumAluthge But I don't see how the code differs from what was initially there.  Any idea what was the reason for the silent failures?

**Comment by DilumAluthge** [comment]
Yeah. The YAML wasn't getting parsed correctly. So while we had intended to write this:

```
@info "attempting to build the docs"
run(`julia --project=docs docs/make.jl`)
```

Where that would have been two separate lines, we instead wrote this:

```
@info "attempting to build the docs" run(`julia --project=docs docs/make.jl`)
```

Where it all became one line. So it was equivalent to writing the following in Julia:


```
@info "my message" f()
```

In Julia, if you write `@info "my message" f()`, and if `f()` throws an exception, the overall `@info` will NOT throw an exception; it will print a warning message, but it will not error.

**Comment by ablaom** [comment]
Thanks for that @DilumAluthge . Can we have a "restore" commit so that docs don't get generated on PR's to dev.

**Review by ablaom — APPROVED** [review]
Good to go!

Thanks @DilumAluthge for jumping in here.

**Comment by DilumAluthge** [comment]
@ablaom Can you make a PR to merge dev into master?

**Comment by ablaom** [comment]
I was first going to fix the cause of the fail (tracking this at #1045). I  haven't got around to that.

**Pull request merged**
