### PR TITLE
[WIP] Add Dagger integration for learning networks

### PR DESCRIPTION
**Pull request by jpsamaroo**
Status: Works only on master process, not well tested

TODO:
- [x] Pass tests with master
- [ ] Pass tests with single worker
- [ ] Pass tests with multiple workers
- [x] Allow disabling multiprocessing/force computations to master - ~relies on https://github.com/JuliaParallel/Dagger.jl/pull/107~
- [ ] Be reasonably efficient with data placement and movement
- [ ] Add documentation
- [ ] Remove/clean up extra debugging statements and vestigial code

Closes https://github.com/alan-turing-institute/MLJ.jl/issues/72

### CODE REVIEW

**Comment by jpsamaroo** [comment]
I realized that I locally started working on adding Dagger support to model evaluation too, which wasn't originally requested in #72. Before I revert my (local) changes, @ablaom would you also want to see model evaluation parallelized? If the learned parameters are already on other workers from a previous round of training, the parameters are large, and the machines are individually expensive to evaluate, it could make sense to also extend Dagger support to model evaluation.

**Comment by ablaom** [comment]
Thanks for that. 

Is it possible to split these into separate PR's without too much bother?

**Comment by jpsamaroo** [comment]
Absolutely, I'll put those changes into a future PR which will be based on this one.

**Comment by jpsamaroo** [comment]
I figured out why I'm having issues running MLJ on a non-master worker: Julia's Distributed functionality doesn't automatically synchronize modified state from the workers back to the master (such as the `fitresult` of each machine after fitting); this isn't a bug in the Distributed stdlib, but it also isn't immediately obvious (since changes on the master *do* get propagated to the workers).

I am going to work around this by explicitly copying over all model fields from the worker to the master each time a machine is fit; a more efficient approach can be investigated once things are working, and may involve some changes to Dagger.

**Comment by jpsamaroo** [comment]
Rebased onto master, still WIP (currently broken as I change things around)

Update: I'm working on the approach for ensuring synchrony of the learning network across workers as needed. At each `fit!` call, I'm "reducing" a network done to simpler nodes which only record their arguments as UUIDs, and broadcasting that to all workers (which then re-constitute them as a regular learning network). This is necessary so that we can identify which nodes are the same between workers, even when they've been fit or modified (since otherwise there's no way for two workers to determine which of their local nodes are "the same", and thus no easy way to synchronize the network to the next worker that needs the most up-to-date copy).

I'm switching things around right now to fix some issues, and then hopefully things will all work correctly. Things aren't terribly efficient right now (we have a lot of overhead for each `fit!` call, and maybe transfer more data than necessary), but hopefully I'll be able to make things more efficient once I've gotten everything to run correctly.

**Comment by ablaom** [comment]
@jpsamaroo Could you say a few words about why you want to make Nodes mutable?

**Comment by jpsamaroo** [comment]
It's possible that this isn't required, I probably put that in thinking that I needed it. As long as NodalMachines are mutable, then I think that should all that's needed. I'll check if I can make Node immutable again without breaking the approach this PR takes before I'm done.

**Comment by ablaom** [comment]
No worries. FYI source nodes are mutable on master and there is a rebind! method for altering contents

**Comment by jpsamaroo** [comment]
@ablaom I thought about this again, and just realized that I'll actually need `Node`s to be mutable. Without this, I would have to create a new node on each `fit!` invocation, which will both break any existing user references to that node, but even worse, means that we *always* have to recreate downstream nodes of the network anytime we want to change just a single upstream node (since, in the downstream nodes, the `args` fields of `Node` is not an internally mutable object). I'm confident that making `Node` mutable will not harm performance or functionality in any significant way.

**Comment by ablaom** [comment]
Okay, all good.

**Comment by jpsamaroo** [comment]
The latest commit (temporarily?) disables log tests to preserve my sanity and make it possible to use CI to test my changes. Hopefully we can figure out another way to test that things happen in the right order.

**Comment by jpsamaroo** [comment]
So, the current tests that're failing are `test/tuning.jl` line 48, where `tuned.report.measurements` is tested for uniqueness (in this PR it's about only 25% unique), and line 51, where we check that `length(b.transformer.features) == 3`. Given my non-familiarity with what's going on in this block of code, would someone mind explaining *why* these two tests should pass? Just a high-level overview of why `tuned.report.measurements` should be unique, and why `b.transformer.features` should have length of 3, would be great. Hopefully fixing these tests will uncover a piece of logic that I'm failing to account for.

**Comment by ablaom** [comment]
The tests to which you refer should pass. (There was a possibility of failure "in  rare cases" which I have eliminated on master by seeding the random  generator with a fixed seed.) What we are doing in this tuning is evaluating the performance (RMS loss) of a ridge model with feature preselection for a different numbers of features and different values of the regularisation parameter :lambda. So each `measurement` is for different values of these two  parameters. You would expect different losses in each case and this is confirmed by the tests on master. If you switch on verbosity=2 in fit you can see this detail:

```
transformer.features=Symbol[:x1]        model.lambda=1.0e-6     measurement=1.956173585332149
transformer.features=Symbol[:x1, :x2]   model.lambda=1.0e-6     measurement=0.9722751273094239
transformer.features=Symbol[:x2, :x3]   model.lambda=1.0e-6     measurement=0.5960356038449827
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=1.0e-6     measurement=0.06531909204846562
transformer.features=Symbol[:x1]        model.lambda=3.5938136638046257e-6      measurement=1.9561736077764658
transformer.features=Symbol[:x1, :x2]   model.lambda=3.5938136638046257e-6      measurement=0.972275089262771
transformer.features=Symbol[:x2, :x3]   model.lambda=3.5938136638046257e-6      measurement=0.596035698835706
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=3.5938136638046257e-6      measurement=0.06531894272077685
transformer.features=Symbol[:x1]        model.lambda=1.2915496650148827e-5      measurement=1.956173688437353
transformer.features=Symbol[:x1, :x2]   model.lambda=1.2915496650148827e-5      measurement=0.9722749525306037
transformer.features=Symbol[:x2, :x3]   model.lambda=1.2915496650148827e-5      measurement=0.5960360402210935
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=1.2915496650148827e-5      measurement=0.06531840611748886
transformer.features=Symbol[:x1]        model.lambda=4.641588833612782e-5       measurement=1.9561739783200762
transformer.features=Symbol[:x1, :x2]   model.lambda=4.641588833612782e-5       measurement=0.972274461146022
transformer.features=Symbol[:x2, :x3]   model.lambda=4.641588833612782e-5       measurement=0.5960372671795916
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=4.641588833612782e-5       measurement=0.06531647834466271
transformer.features=Symbol[:x1]        model.lambda=0.0001668100537200059      measurement=1.9561750201371555
transformer.features=Symbol[:x1, :x2]   model.lambda=0.0001668100537200059      measurement=0.9722726952704881
transformer.features=Symbol[:x2, :x3]   model.lambda=0.0001668100537200059      measurement=0.5960416777122076
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=0.0001668100537200059      measurement=0.06530955906488609
transformer.features=Symbol[:x1]        model.lambda=0.0005994842503189409      measurement=1.9561787646545088
transformer.features=Symbol[:x1, :x2]   model.lambda=0.0005994842503189409      measurement=0.9722663499353807
transformer.features=Symbol[:x2, :x3]   model.lambda=0.0005994842503189409      measurement=0.596057542197002
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=0.0005994842503189409      measurement=0.06528480589627572
transformer.features=Symbol[:x1]        model.lambda=0.0021544346900318843      measurement=1.9561922271890888
transformer.features=Symbol[:x1, :x2]   model.lambda=0.0021544346900318843      measurement=0.9722435575189401
transformer.features=Symbol[:x2, :x3]   model.lambda=0.0021544346900318843      measurement=0.5961147351955126
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=0.0021544346900318843      measurement=0.0651973163751434
transformer.features=Symbol[:x1]        model.lambda=0.007742636826811269       measurement=1.9562406792892024
transformer.features=Symbol[:x1, :x2]   model.lambda=0.007742636826811269       measurement=0.972161795194888
transformer.features=Symbol[:x2, :x3]   model.lambda=0.007742636826811269       measurement=0.5963225919682634
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=0.007742636826811269       measurement=0.06490203405403161
transformer.features=Symbol[:x1]        model.lambda=0.027825594022071243       measurement=1.95641571633127
transformer.features=Symbol[:x1, :x2]   model.lambda=0.027825594022071243       measurement=0.9718699039072604
transformer.features=Symbol[:x2, :x3]   model.lambda=0.027825594022071243       measurement=0.5970996842645402
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=0.027825594022071243       measurement=0.06409534301049373
transformer.features=Symbol[:x1]        model.lambda=0.1        measurement=1.9570565933336332
transformer.features=Symbol[:x1, :x2]   model.lambda=0.1        measurement=0.9708469086073229
transformer.features=Symbol[:x2, :x3]   model.lambda=0.1        measurement=0.6002896336658909
transformer.features=Symbol[:x1, :x2, :x3]      model.lambda=0.1        measurement=0.0647065516108381
```

These results should not depend on whether a scheduler is being  used to implement  training of the underlying (very simple two-component) learning network. 

Note that there is no existing parallelization of tuning yet. (Now tuning fits `resampling` machines, and these `fit` methods are parallelized in the existing code, but only if `resampling=CV`, which is not the case here, but maybe elsewhere. I just mention this, because the CV parallel code is not tested currently).

The length value tested is the number of features in the optimal model. On master this is found to be three (the maximum number tried) and this again should not depend on the scheduler.

Is this sufficiently helpful?

**Comment by jpsamaroo** [comment]
Awesome, thanks @ablaom ! The `verbosity=2` kwarg made it clear that, for some reason, `model.lambda` is having issues with being tuned, whereas `transformer.features` is being tuned appropriately, hence the 25% uniqueness. I should be able to figure this one out pretty quickly now that I have this information to go off of. It also looks like the other test failure is related to this; solving the first failure should make the solution to the second obvious I think.

Unrelated: I'm going to hold off on rebasing until I get this current set of code working as needed. I require this to maintain my sanity, just in case you're wondering :slightly_smiling_face:

**Comment by ablaom** [comment]
Your sanity is definitely the higher priority.

**Comment by jpsamaroo** [comment]
Closing this since it's probably not going to be worked on anytime soon. I'll keep the branch around on my fork.

**Comment by ablaom** [comment]
Now worries. See my slack message, thanks.

**Pull request closed without merging**
