### PR TITLE
WIP + RFC. Add simple plotting recipe. Fix #85

### LINKED ISSUE #85: Visualization tool for one and two-parameter tuning
Would be nice to have some visualization tools (Plots.jl recipes?) for looking at the results of one or two-parameter tuning, as ouput in the `report` field of a `TunedModel` machine. 

This might be as simple as adding a suitable instruction to the tuning doc string on how to call an existing recipe.

* [x] two-parameter case
* [ ] one-parameter case (to include uncertainty of performance measurements)

### PR DESCRIPTION
**Pull request by mkborregaard**

### CODE REVIEW

**Comment by mkborregaard** [comment]
A simple recipe for plotting. Right now it's the default plot for tuned models, that can be changed if that is not desired. It uses colored scatter points. There's an option for using heatmap also, but that currently behaves strangely for log scales. That seems to be a bug in Plots though, I think the recipe here is fine.

Using the `tuned_ensemble` object generated from here, you can do:
```julia
plot(tuned_ensemble)
```
tune1

The heatmap version (you can also use `surface` or `contour`):
```julia
heatmap(tuned_model)
```
tune2

**Comment by ablaom** [comment]
This looks super. 

I'm having some problems though. Any ideas?

I'm using Plots.jl v0.23.1 

````julia
julia> using Plots
julia> Plots.backend()
Plots.GRBackend()

julia> include("examples/two_parameter_tune.jl")
julia> tuned_ensemble isa MLJ.Machine{<:MLJ.EitherTunedModel}
true

julia> plot(tuned_ensemble)
ERROR: No user recipe defined for Machine{MLJ.DeterministicTunedModel{Grid,DeterministicEnsembleModel{Tuple{Array{Float64,2},Array{Float64,1}},KNNRegressor{Float64}}}}
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] convertToAnyVector(::Machine{MLJ.DeterministicTunedModel{Grid,DeterministicEnsembleModel{Tuple{Array{Float64,2},Array{Float64,1}},KNNRegressor{Float64}}}}, ::Dict{Symbol,Any}) at /Users/anthony/.julia/packages/Plots/gylTh/src/series.jl:14
 [3] macro expansion at /Users/anthony/.julia/packages/Plots/gylTh/src/series.jl:139 [inlined]
 [4] apply_recipe(::Dict{Symbol,Any}, ::Type{Plots.SliceIt}, ::Nothing, ::Machine{MLJ.DeterministicTunedModel{Grid,DeterministicEnsembleModel{Tuple{Array{Float64,2},Array{Float64,1}},KNNRegressor{Float64}}}}, ::Nothing) at /Users/anthony/.julia/packages/RecipesBase/Uz5AO/src/RecipesBase.jl:275
 [5] _process_userrecipes(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Machine{MLJ.DeterministicTunedModel{Grid,DeterministicEnsembleModel{Tuple{Array{Float64,2},Array{Float64,1}},KNNRegressor{Float64}}}}}) at /Users/anthony/.julia/packages/Plots/gylTh/src/pipeline.jl:83
 [6] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Machine{MLJ.DeterministicTunedModel{Grid,DeterministicEnsembleModel{Tuple{Array{Float64,2},Array{Float64,1}},KNNRegressor{Float64}}}}}) at /Users/anthony/.julia/packages/Plots/gylTh/src/plot.jl:178
 [7] #plot#136(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Machine{MLJ.DeterministicTunedModel{Grid,DeterministicEnsembleModel{Tuple{Array{Float64,2},Array{Float64,1}},KNNRegressor{Float64}}}}) at /Users/anthony/.julia/packages/Plots/gylTh/src/plot.jl:57
 [8] plot(::Machine{MLJ.DeterministicTunedModel{Grid,DeterministicEnsembleModel{Tuple{Array{Float64,2},Array{Float64,1}},KNNRegressor{Float64}}}}) at /Users/anthony/.julia/packages/Plots/gylTh/src/plot.jl:51
 [9] top-level scope at none:0

julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
Environment:
  JULIA_PATH = /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia

````

**Comment by mkborregaard** [comment]
Sure I've added the suggested test, though this adds Plots as a testing dependency. 
It looks like you may just not have the right branch checked out though.

**Comment by mkborregaard** [comment]
Seems to work for Travis.

**Comment by ablaom** [comment]
Yes, my mistake. In a recent rebuild of my working env I had done `add` instead of `dev` of the MLJ repos. It works great. 

I'd like to pull this before adding a 1-parameter version (there was some discussion of adding uncertainty estimates in this case). @mkborregaard Could you please:

- add a check on the number of parameters and do `error("Only two-parameter tuning plots supported") if the number is two?

- remove the test and Plots dependency

@fkiraly Are you happy for me to pull this?

**Comment by mkborregaard** [comment]
I can - just to make sure, the test doesn't add Plots as a dependency, just as a test dependency. But you'd still like me to remove it again?

**Comment by ablaom** [comment]
Yes, let's leave it out for now thanks.

**Pull request merged**
