### PR TITLE
Readme review

### PR DESCRIPTION
**Pull request by ablaom**
Redistribute the readme contents over CONTRIBUTING.md, ORGANIZATION.md, ROADMAP.md

### CODE REVIEW

**Comment by ablaom** [comment]
@tlienart No need for a formal review but comments very welcome.

**Comment by tlienart** [comment]
Looks good, well done for the snazzy dependency graph. Some very minor comments:

**Readme**
- mention the arrow direction in the graph label (`A --> B` means that `A` depends on `B`)
- maybe what would be nice is to have colours for the different packages in that schema like Green for what users are expected to use (MLJ, MLJLM, MLJF, 3dParty), Blue for devs (MLJBase, MLJModelInterface, MLJScientificTypes, MLJTuning, MLJEnsembles, MLJMeasures), and Orange for generic (ScientificTypes) 

**Contribution**
- mention Invenia's blue style if we're happy to generally follow those guidelines (#434) + the 80 char width
- mention that, as far as possible, every new feature should be tested

**Comment by ablaom** [comment]
Done, thanks!

**Comment by ablaom** [comment]
Closing and re-opening as PR to dev

**Pull request closed without merging**
