### PR TITLE
For a 0.16 release

### PR DESCRIPTION
**Pull request by ablaom**
Release notes:

Update MLJModels and MLJBase requirements. Includes some breaking changes, in particular around the use of `@load`. For details see:

[MLJBase 0.17.0 release notes](https://github.com/alan-turing-institute/MLJBase.jl/releases/tag/v0.17.0)
[MLJModels 0.14.0 release notes](https://github.com/alan-turing-institute/MLJModels.jl/releases/tag/v0.14.0)

### CODE REVIEW

**Comment by ablaom** [comment]
Docs failing:

```
      Added registry `General` to `~/.julia/registries/General`
ERROR: expected package `NearestNeighborModels [636a865e]` to be registered
Stacktrace:
 [1] pkgerror(::String) at 
```

Weird. Perhaps ci version of General.jl is not up-to-date??

(docs build locally fine)

Will try to restart tests.

**Comment by ablaom** [comment]
@DilumAluthge Any idea why ci reports that [`NearestNeighborModels.jl`](https://github.com/JuliaRegistries/General/blob/master/N/NearestNeighborModels/Versions.toml) is not registered?

**Comment by DilumAluthge** [comment]
Yeah you should turn off Pkg server

**Comment by DilumAluthge** [comment]
Basically something like this:
```yaml
env:
  JULIA_PKG_SERVER: ""
```

Add that to the step in the docs build that calls Pkg.instantiate.

**Comment by ablaom** [comment]
@DilumAluthge Thanks! I'll give that a try.

**Comment by ablaom** [comment]
@DilumAluthge That fixed it, many thanks. ❤️

**Pull request merged**
