### PR TITLE
Add parallelism tests for resampling

### LINKED ISSUE #207: Add testing for existing parallelisation of resampling
There are  currently no tests for the existing "parallel=true" option in `evaluate!`. It would be nice to  have this added and perhaps have the existing implementation reviewed. 

This method recently was recently refactored (#206), so be sure to work off master.

### PR DESCRIPTION
**Pull request by jpsamaroo**
I set the number of workers to 2 since that's what the current code in `src/resampling.jl` tests to enable parallel execution.

Closes #207

### CODE REVIEW

**Comment by ablaom** [comment]
Many thanks! I guess this is a WIP, as I see travis tests failing:

UndefVarError: .^ not defined

**Comment by jpsamaroo** [comment]
Yes, sorry, adjusted the PR title to match the status.

The error I see locally is different (but still an UndefVarErro), related to the fact that the test modules don't exist on remote workers by default (which becomes a problem when a worker tries to deserialize a value which has a test module as its parent module). I doubt it'll be tough to fix, I just haven't gotten around to investigating further.

**Comment by jpsamaroo** [comment]
I'm not 100% sure what black magic is occurring to break the "folds specified" tests, and I'm not sure I feel like delaying the rest of this PR to find out. @ablaom would it be alright if we leave those tests running only in serial, and come back to this at a later point?

**Comment by ablaom** [comment]
Many thanks for this. I've had a look at this and this is what I learnt. 

1. Presently most (all?) test files have the test code wrapped in a module, eg, `resampling.jl` has code wrapped in `module TestResampling ... end true`. This seems to cause testing parallel code problems. Did you encounter this problem?

2. If I remove the module wrapping, I can resolve your issue. Currently you have this macro:

```julia
macro test_parallel(var, ex)
    quote
        $(esc(var)) = false
        $ex
        $(esc(var)) = true
        $ex
    end
end
```

If you escape the whole quote, as here:

```julia
macro test_parallel(var, ex)
    esc(quote
        $var = false
        $ex
        $var = true
        $ex
    end)
end
```
Then the error goes away, in addition to some other errors I encountered later in the code, which were better clues to the problem (the "resampling as machines" block). 

@jpsamaroo Do you think you could have another look at this? I'm not sure what the solution to 1. is. Do we insert `@everywhere` before each module definition or something? The module wraps are there to avoid namespace clashes. Maybe there's a better way to do this. Can't just use @testset blocks because: (i) In julia 1.0 you can't put `using` statements in them and (ii) they don't seem to work around tests of certain macros, for reasons I could not understand (`eval`s within baremodules or something?).

**Comment by ablaom** [comment]
BTW, we are now merging new PRs into dev branches. Master branch is for tagged releases only.

**Comment by jpsamaroo** [comment]
I see, that's rather annoying. Should we file an issue to Julia upstream and wait for a response before moving forward on this?

**Comment by ablaom** [comment]
Feel free to post an issue with Julia. However, the expedient thing to do is just dump the hygiene, as suggested by my earlier comment, unless you really see a need for it.

**Comment by jpsamaroo** [comment]
If by hygiene you mean the test wrapper, then I'm happy to do so. I'm also happy to file an issue to Julia if we can make an MWE that doesn't rely on MLJ (not required, but it makes it easier for more people to assist debugging).

**Comment by ablaom** [comment]
Yes, just escape the whole `@test_paralllel` expression. Re WIP, feel free to investigate, but this is low on my priorities right now, sorry.

**Comment by jpsamaroo** [comment]
Changed to single `esc` hygiene and rebased on dev. If tests pass, then I'd be happy to have this merged.

**Comment by jpsamaroo** [comment]
No idea why `TestTuning` is running into the same serialization error now...

**Comment by jpsamaroo** [comment]
I've improved the `@testset_accelerated` (previously `@testset_parallel`) so that we can test multiprocessing and multithreading. Right now the only errors I get locally are related to deserializing the `TestResampling` module on the workers for `CPUProcesses`. I'll continue investigating a solution.

**Comment by jpsamaroo** [comment]
@ablaom how would you feel about me just marking the failing tests (for specific resources) as broken? If we do this, we could merge this PR and then reuse the same mechanism to test everything else that can be accelerated, and then eventually we might figure out how to fix the currently-broken tests.

**Comment by ablaom** [comment]
I think that's a good idea. Ping me when that is done and I'll try to look over them too. Sometimes the issue may be related to random number generation which is, as we know too well, is difficult to reproduce the same in parallel as in in serial computing.

**Comment by ablaom** [comment]
@jpsamaroo Incidentally, thanks heaps for having another look at this! ❤️

**Comment by jpsamaroo** [comment]
@ablaom did we ever figure out why `UndefVarError: .^ not defined` and similar errors occur? It seems like those are preventing 1.0 and 1.1 tests from passing (while 1.2 passes).

**Comment by jpsamaroo** [comment]
Ahh, I forgot `esc()` during the refactor. Ready for review!

**Comment by ablaom** [comment]
Awesome!! 

It looks like none of the tests for multithreading are broken, which is interesting and encouraging 💪 

One last request. Can we please also wrap the test starting at line 271 of test/resampling.jl as an accelerated test (possibly with exclusions for the breaking bits)?

**Comment by jpsamaroo** [comment]
Multithreading passing might not mean much since we don't set `JULIA_NUM_THREADS`, but it's certainly better than nothing!

Latest commit enables final test (which I didn't enable because it exhibited failure before adding back macro hygiene).

**Pull request merged**
