### PR TITLE
Export `JointProbabilistic` and `predict_joint`

### PR DESCRIPTION
**Pull request by DilumAluthge**
@ablaom Let me know if I missed anything.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Bump @ablaom @tlienart

**Comment by ablaom** [comment]
This needs an update on [compat] MLJModelInterface, no?

**Comment by ablaom** [comment]
We need to wait for the next tagged release of MLJBase (the exports there are on dev)

**Comment by DilumAluthge** [comment]
Sounds good. Once the new release of MLJBase is tagged, I'll update the compat entry here accordingly.

**Comment by ablaom** [comment]
@DilumAluthge Can you please bump (in this PR) the MLJBase [compat] to "^0.14.9" (just merged)?

**Comment by DilumAluthge** [comment]
Done!

**Pull request merged**
