### PR TITLE
Remove type piracy

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by ablaom** [comment]
Let's keep the piracy for now:

https://github.com/JuliaStdlibs/Random.jl/issues/1

**Comment by giordano** [comment]
I don't think standard libraries are maintained there (not yet, at least).  Issues should probably be raised directly in Julia's repo

**Comment by ablaom** [comment]
https://github.com/JuliaLang/julia/issues/32173

**Comment by jpsamaroo** [comment]
Some more type piracy I found:

https://github.com/alan-turing-institute/MLJ.jl/blob/b2c49568caf6b64a794c8a2a9400b1e9e2909052/src/networks.jl#L44
https://github.com/alan-turing-institute/MLJ.jl/blob/b2c49568caf6b64a794c8a2a9400b1e9e2909052/src/networks.jl#L357

**Comment by ablaom** [comment]
@jpsamaroo Thanks for that. 

Yes, merge! can just be renamed. Part of the log piracy is justified, part not. We could replace

```julia
Base.log(v::Vector{<:Number}) = log.(v)
Base.exp(v::Vector{<:Number}) = exp.(v)
Base.log(X::AbstractNode) = node(log, X)
Base.exp(X::AbstractNode) = node(exp, X)
```
with

```julia
Base.log(X::AbstractNode) = node(XX->log.(XX), X)
Base.exp(X::AbstractNode) = node(XX->exp.(XX), X)
```

**Comment by ablaom** [comment]
I've removed log, exp type piracy. Closing this pull. Can remove the show when https://github.com/JuliaLang/julia/issues/32173 is resolved

**Pull request closed without merging**
