### PR TITLE
For tagged release 0.5.0

### PR DESCRIPTION
**Pull request by ablaom**
https://github.com/JuliaRegistries/General/pull/3863

### CODE REVIEW

**Comment by ablaom** [comment]
This will fail until MLJModels 0.5.0 is official.

**Comment by ablaom** [comment]
@tlienart 

I think the nightly fail is due to use of `Pkg.installed()` in src/MLJ.jl. I guess this has been depreciated or something.  I am happy for this to be merged, but wanted this noted.

**Comment by tlienart** [comment]
`Pkg.installed()` works fine on 1.4. Could you point me to the place where you use it? If it's unqualified (like `installed()`) could you qualify it? (even if you import it explicitly; if it's used in init most likely you must qualify)

**Comment by ablaom** [comment]
this line from src/MLJ.jl:

```julia
const MLJ_VERSION = Pkg.installed()["MLJ"]
```

**Comment by giordano** [comment]
Should be something like
```julia
uuid = Pkg.project().dependencies["MLJ"]
version = Pkg.dependencies()[uuid].version
```

**Comment by ablaom** [comment]
@tlienart 

Please merge when you're happy and register the new version with release notes copied verbatim from #239.

**Comment by giordano** [comment]
@tlienart `Pkg.installed()` does _not_ work fine on 1.4, it has been completely removed: https://github.com/JuliaLang/Pkg.jl/pull/1086

**Comment by tlienart** [comment]
> @tlienart `Pkg.installed()` does _not_ work fine on 1.4, it has been completely removed: [JuliaLang/Pkg.jl#1086](https://github.com/JuliaLang/Pkg.jl/pull/1086)

Thanks for poiting out the PR, I'll have a look (btw: I'm on 1.4 dev 143 and I did not make up that the tests pass locally I guess this is a recent enough modification)

**Comment by giordano** [comment]
A couple of days ago someone asked what happened to Pkg.installed in julia master. I think it was merged in master with https://github.com/JuliaLang/julia/pull/33364, and then reverted a few hours ago in https://github.com/JuliaLang/julia/pull/33410, but I guess that in the long term is not safe to rely on Pkg.installed

**Comment by tlienart** [comment]
> A couple of days ago someone asked what happened to Pkg.installed in julia master. I think it was merged in master with [JuliaLang/julia#33364](https://github.com/JuliaLang/julia/pull/33364), and then reverted a few hours ago in [JuliaLang/julia#33410](https://github.com/JuliaLang/julia/pull/33410), but I guess that in the long term is not safe to rely on Pkg.installed

do you know what's meant to replace it? is it the `Pkg.project`? thanks

**Comment by giordano** [comment]
I wrote above how to replace `Pkg.installed`: https://github.com/alan-turing-institute/MLJ.jl/pull/246#issuecomment-536228681

**Comment by tlienart** [comment]
> I wrote above how to replace `Pkg.installed`: [#246 (comment)](https://github.com/alan-turing-institute/MLJ.jl/pull/246#issuecomment-536228681)

thanks, sorry about that

**Pull request merged**
