### PR TITLE
Updated names of BetaML models

### PR DESCRIPTION
**Pull request by sylvaticus**

### CODE REVIEW

**Comment by sylvaticus** [comment]
it should have been rebased now... or so I think..

**Review by ablaom — APPROVED** [review]
Looks good. Thanks!

**Comment by sylvaticus** [comment]
Hello, something didn't work well with this PR.. the [List of supported models (dev)](https://alan-turing-institute.github.io/MLJ.jl/dev/list_of_supported_models/) page is still referring to the very old BetaML-MLJ interface names... 

(minor typo: also in the meantime I realised there is no `MultitargetGaussianMixtureImputer`)

**Comment by ablaom** [comment]
Yeah,  that page has to be updated manually. Thanks for pointing this out. 

https://github.com/alan-turing-institute/MLJ.jl/issues/993

**Pull request merged**
