### PR TITLE
Test change

### PR DESCRIPTION
**Pull request by ysimillides**
Renamed the tests, and made them consistent with the module names

### CODE REVIEW

**Comment by ablaom** [comment]
Sorry Yiannes, I have pushed some changes that introduce conflicts with your PR. Can you please try to resolves these?

**Comment by ysimillides** [comment]
Yes that sounds fine. I'll fix it over the weekend.

**Comment by fkiraly** [comment]
Short, related question: if you are setting up unit tests, why not use a "proper" CI framework? E.g., https://travis-ci.org/

**Comment by ysimillides** [comment]
I already set up Travis some time ago and it's running with each PR/commit
________________________________

**Comment by ablaom** [comment]
Yiannes, 

Please hold off pursuing this PR. I have had second thoughts. This change means adopting new naming conventions which is a complication. Using the same name for src/ and test/ is simpler and less ambiguous. The fall path mitigates all ambiguity.

**Pull request closed without merging**
