### PR TITLE
Cleaned up Adding Models for General Use documentation

### PR DESCRIPTION
**Pull request by antoninkriz**
Minor cleanup of some mistakes in the documentation I stumbled upon when implementing a new model

### CODE REVIEW

**Review by ablaom — APPROVED** [review]
Looks good to me. Much appreciated. 

Let me know if you need further guidance implementing your interface.

**Comment by ablaom** [comment]
@antoninkriz Do you mind rebasing your PR so as to make `dev` branch the target?

**Comment by antoninkriz** [comment]
@ablaom Done, thank you!
The `master` branch was a missclick, I shoud've noticed it sooner.

**Review by ablaom — APPROVED** [review]
thanks again

**Pull request merged**
