### PR TITLE
PCA from MultivariateStats.jl

### PR DESCRIPTION
**Pull request by tlienart**
Note the `collect(transpose(...))` machinery (cf #50). See also https://github.com/JuliaStats/Clustering.jl/issues/136 and the corresponding PR and the discussion: https://discourse.julialang.org/t/function-on-matrix-transpose-and-performance/20068/5

The rest is standard as far as I can tell.

### CODE REVIEW

**Comment by ablaom** [comment]
This looks good. 

(i) Note however that a interface implementation for MultivariateStats was already started at builtins/LocalMultivariateStats.jl  . I wanted the RidgeRegressor built-in for testing purposes. I think it could move but I have to fix the tests and move the dependency to [extras], and so forth. This can happen when we move everything to planned separate package MLJModels.jl . Can you please add your code to LocalMultivariateStats.jl for now and drop the lazy load?

(ii) At our last meeting there was agreement that dimension-reducing transformers (and perhaps all Unsupervised models) should return a table instead of matrix. (If you have a dissenting opinion, feel free to raise an issue.) There is a materialising function in MLJBase for the conversion - not yet pushed to master - but let's add tabularization of output of your transformers after we pull this PR.

**Comment by tlienart** [comment]
> This looks good.
> 
> (i) Note however that a interface implementation for MultivariateStats was already started at builtins/LocalMultivariateStats.jl . I wanted the RidgeRegressor built-in for testing purposes. I think it could move but I have to fix the tests and move the dependency to [extras], and so forth. This can happen when we move everything to planned separate package MLJModels.jl . Can you please add your code to LocalMultivariateStats.jl for now and drop the lazy load?

I had seen LocalMultivariateStats and wasn't sure whether the code was better there or in a file, I'll change following your suggestion.

> (ii) At our last meeting there was agreement that dimension-reducing transformers (and perhaps all Unsupervised models) should return a table instead of matrix. (If you have a dissenting opinion, feel free to raise an issue.) There is a materialising function in MLJBase for the conversion - not yet pushed to master - but let's add tabularization of output of your transformers after we pull this PR.

I think that makes sense. A complicating element to keep in mind is that in some cases (most in memory DBs) it'll just be quicker to work on the matrix of values, that could mean a fair bit of conversions back and forth. 

Anyway, could you clarify what you want me to do for this one? wait for the conversion back to `Table` to be pushed and used that instead of the outermost `copy(transpose...)` that I had used?

**Comment by tlienart** [comment]
done

**Comment by ablaom** [comment]
Thanks!!

**Pull request merged**
