### PR TITLE
Fix #192: Add verbosity option to @load macro

### LINKED ISSUE #192: Control verbosity of @load macro
**Is your feature request related to a problem? Please describe.**
Whenever I load a model in a script, I get verbose information about the packages being loaded.

**Describe the solution you'd like**
I would like to control this verbosity, possibly by using an alternative macro. `@load` would be quiet, and then `@loaddbg` would print information about package imports.

**Describe alternatives you've considered**
An alternative would be to make `@load` quiet, and to not introduce a `@loaddbg`.

**Additional context**
The context is normal usage. I would like to try out a couple of models in a problem, and the messages printed can get annoying quickly.

### PR DESCRIPTION
**Pull request by juliohm**
This PR adds an option `verbosity` to `@load` which defaults to 0. Printing can get quite annoying for heavy ML research.

Fixes #192

### CODE REVIEW

**Comment by juliohm** [comment]
It seems like some changes were made to the master branch a few minutes ago that invalidated this PR. Could you please take a look and rebase maybe?

**Comment by giordano** [comment]
> It seems like some changes were made to the master branch a few minutes ago that invalidated this PR

I think you're working on an old branch (of mid June), the last commit to this file has been two weeks ago.

**Comment by juliohm** [comment]
Interesting, I think it was my incorrect assumption again that `] up` pulls the master of dev'ed packages.

Will submit another one.

**Comment by giordano** [comment]
No, you have to manually pull those repositories, julia package manager doesn't mess up with them, and I think this is a good feature

**Pull request closed without merging**
